AWSTemplateFormatVersion: 2010-09-09

Description: Common template for provisioning resources needed for the Challenges

Parameters:
  SubdomainPrefix:
    Default: ADC
    Description: Please enter the subdomain prefix
    Type: String

Resources:
  ADCVPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: vpc.yml
  ADCRDSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: rds.yml
      Parameters:
        DBAppCIDRs:
          Fn::Join:
            - ','
            -
              - Fn::GetAtt:
                  - ADCVPCStack
                  - Outputs.PrivateSubnetACDIR
              - Fn::GetAtt:
                  - ADCVPCStack
                  - Outputs.PrivateSubnetBCDIR
        VPCId:
          Fn::GetAtt:
            - ADCVPCStack
            - Outputs.VPCId
        DBSubnetGroupIDs:
          Fn::Join:
            - ','
            -
              - Fn::GetAtt:
                  - ADCVPCStack
                  - Outputs.DatabaseSubnetA
              - Fn::GetAtt:
                  - ADCVPCStack
                  - Outputs.DatabaseSubnetB
